name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: |
          docker build -t app .

      - name: Run tests
        run: |
          docker-compose run --rm --env PYTHONPATH=. app pytest

      - name: Run lint
        run: |
          docker-compose run --rm --env PYTHONPATH=. app flake8 app/

      - name: Push Docker image to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker tag app ghcr.io/${{ github.repository_owner }}/app:latest
          docker push ghcr.io/${{ github.repository_owner }}/app:latest


